### ISSUE TITLE
0x62是哪個型號的芯片？

### ISSUE THREAD

**Issue by xuefengedu** [lioujj/pxt-lcd1602#1]
劉正吉，你好！ 0x62是哪個型號的芯片？其他的地址是PCF8574和PCF8574A

**Comment by xuefengedu** [comment]
@lioujj any chip use 0x62 address?

**Comment by lioujj** [comment]
http://wiki.seeedstudio.com/Grove-LCD_RGB_Backlight/
我沒有這一個，只是有人和我說他有，問我能否把這個位址放上套件裡

**Comment by xuefengedu** [comment]
ok, thanks for replying! :)

**Comment by xuefengedu** [comment]
Thanks the answer! I got it, so close this issue. :)
